name: 'example'
description: 'A sample command-line application.'
version: '1.0.0'
environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '^3.27.0'
dependencies:
  flutter:
    sdk: 'flutter'
  path: '^1.9.0'
  database_universe: '^0.0.17'
  database_universe_flutter_libs: '^0.0.17'
  general_lib: '^0.0.58'
  general_lib_flutter: '^0.0.39'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
  build_runner: 'any'
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
  database_universe:
    path: '../library/database_universe'
  database_universe_flutter_libs:
    path: '../library/database_universe_flutter_libs'
funding: []
flutter:
  uses-material-design: true
  generate: false
