name: 'database_universe_project'
description: 'Database Universe Library for help you save any data in anywhere with high performance speed, easy feature and ready for scala business'
version: '0.0.16'
homepage: 'https://youtube.com/@azkadev'
repository: 'https://github.com/azkadev/database_universe.git'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://youtube.com/@azkadev'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
environment:
  sdk: '>=3.6.0 <4.0.0'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
dependencies:
  general_lib: '^0.0.58'
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
