name: 'database_universe'
description: 'Database Universe Library for help you create project flutter or dart'

ersion: '0.0.0'
homepage: 'https://github.com/azkadev/database_universe'
repository: 'https://github.com/azkadev/database_universe'
issue_tracker: 'https://github.com/azkadev/database_universe/issues'
documentation: 'https://github.com/azkadev/database_universe/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/azkadev'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment: 
  sdk: '^3.2.3'
dependencies:
  general_lib: ^0.0.37
  path: ^1.9.0
  system_info_fetch: ^0.0.14
dev_dependencies:
  lints: '^2.1.0'
  test: '^1.24.0'
