 
include: package:lints/recommended.yaml

analyzer:
  exclude:
    - example/
    - dev/
    - test/

linter:
  rules:
    - public_member_api_docs
    

# For more information about the core and recommended set of lints, see
# https://dart.dev/go/core-lints

# For additional information about configuring this file, see
# https://dart.dev/guides/language/analysis-options
