name: 'database_universe_inspector'
version: '0.0.16'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  flutter:
    sdk: 'flutter'
  flutter_riverpod: '^2.3.6'
  flutter_svg: '^2.0.7'
  font_awesome_flutter: '^10.5.0'
  go_router: '^10.0.0'
  google_fonts: '^5.1.0'
  database_universe: '^1.0.0'
  vm_service: '^11.9.0'
  web_socket_channel: '^2.4.0'
  general_lib_flutter: '^0.0.40'
  general_lib: '^0.0.59'
  general_framework: '^0.0.14'
dev_dependencies:
  very_good_analysis: '^5.0.0+1'
  build_runner: 'any'
  flutter_lints: '^5.0.0'
flutter:
  uses-material-design: true
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
funding: []
