name: 'database_universe_dart'
description: 'A starting point for Dart libraries or applications.'
version: '1.0.0'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  database_universe_flutter: '^1.0.5'
  database_universe: '^1.0.5'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
project:
  type: ''
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
  - 'https://github.com/sponsors/general-developer'
homepage: 'https://youtube.com/{youtube_username}'
repository: 'https://github.com/{github_username}/{repository_name}'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://youtube.com/{youtube_username}'
