name: 'database_universe_test'
publish_to: 'none'
version: '1.0.0+1'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  collection: '^1.18.0'
  copy_with_extension: '^5.0.3'
  flutter:
    sdk: 'flutter'
  freezed_annotation: '^2.4.1'
  integration_test:
    sdk: 'flutter'
  intl: '^0.19.0'
  database_universe:
    path: '../database_universe'
  database_universe_flutter_libs:
    path: '../database_universe_flutter_libs'
  json_annotation: '^4.8.1'
  meta: '^1.9.1'
  path: '^1.9.0'
  path_provider: '^2.1.5'
  test: 'any'
dev_dependencies:
  build_runner: 'any'
  copy_with_extension_gen: '^5.0.3'
  flutter_test:
    sdk: 'flutter'
  freezed: '^2.4.1'
  json_serializable: '^6.7.1'
  very_good_analysis: '^5.0.0+1'
dependency_overrides:
  database_universe:
    path: '../database_universe'
  database_universe_flutter_libs:
    path: '../database_universe_flutter_libs'
  pointycastle: '3.8.0'
  mime: '^2.0.0'
funding: []
