name: Build Examples

on:
  workflow_dispatch:

jobs:
  build_examples:
    name: Build Examples
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest 
            build_command: flutter build ios --release
          - os: macos-latest 
            build_command: flutter build macos --release
          - os: windows-latest
            build_command: flutter build windows --release
          - os: ubuntu-latest 
            build_command: flutter build linux --release
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4 
      - uses: subosito/flutter-action@v2
        with:
         channel: stable
         flutter-version: 3.29.0

      - name: Build examples/example
        working-directory: examples/example
        run: |
          dart pub get
          flutter pub get
          ${{ matrix.build_command }}

      - name: Build Web examples/example
        working-directory: examples/example
        run: |
          flutter build web --release