name: Testing
on:
  workflow_dispatch:
  
jobs:
  publish:
    name: Publish 
    runs-on: ubuntu-latest-arm
    timeout-minutes: 30
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      